# Generated by Django 5.1.7 on 2025-07-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_order_phone_order_username_alter_order_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="product_images/"),
        ),
    ]
