# Generated by Django 5.1.7 on 2025-07-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_product_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="user",
        ),
        migrations.AddField(
            model_name="cart",
            name="username",
            field=models.CharField(default="unknown", max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, default="unknown", upload_to="product_images/"
            ),
            preserve_default=False,
        ),
    ]
