# Generated by Django 5.1.7 on 2025-07-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_remove_cart_user_cart_username_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, upload_to="../bot/product_images/"),
        ),
    ]
