# Generated by Django 5.1.7 on 2025-07-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_alter_product_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="username",
        ),
        migrations.RemoveField(
            model_name="order",
            name="username",
        ),
        migrations.AddField(
            model_name="cart",
            name="phone",
            field=models.CharField(default=0, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
