# Generated by Django 5.1.7 on 2025-07-05 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0010_remove_cart_username_remove_order_username_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="user",
        ),
    ]
