# Generated by Django 5.1.7 on 2025-07-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0011_remove_order_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="discount_percent",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
