# Generated by Django 5.1.7 on 2025-07-05 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0012_cartitem_discount_percent"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="final_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user.cart"
            ),
        ),
    ]
