# Generated by Django 5.1.7 on 2025-07-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0014_alter_cartitem_cart_alter_cartitem_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="discount_percent",
        ),
        migrations.AddField(
            model_name="product",
            name="discount_percent",
            field=models.PositiveIntegerField(default=0, help_text="Скидка в процентах"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="product_images/"),
        ),
        migrations.DeleteModel(
            name="Promotion",
        ),
    ]
