# Generated by Django 5.1.7 on 2025-07-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0015_remove_cartitem_discount_percent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="is_new",
            field=models.BooleanField(default=True),
        ),
    ]
