# Generated by Django 5.1.7 on 2025-07-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0016_orderitem_is_new"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="is_new",
        ),
        migrations.AddField(
            model_name="order",
            name="is_new",
            field=models.BooleanField(default=True),
        ),
    ]
